[build]
  publish = "."

[[redirects]]
  from = "https://www.digitalbizlab.net/*"
  to = "https://digitalbizlab.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
